### ISSUE TITLE
Add ability to cache maps

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-cps#1]
@benismobile where do you want the button to appear?

**Comment by benismobile** [comment]
It would be best to have the cached maps pre-installed, or for a hard coded area to be downloaded the first time the app is opened.

**Comment by gmh04** [comment]
I think having the map download first time app starts will be easier to do.  Otherwise we will need to ship an sqllite datasbase with app, which for IOS could be a problem, or at least an unknown.

I suggest adding:
- a button to download fixed area, should initial download fail (e.g no network)
- a button to view saved maps
- optionally a button to create a saved map

**Comment by benismobile** [comment]
yes - they way I see this going eventually is that the cached map area could be specified as part of the form. Assuming you have some flag that tells the app whether the map area for the form has been cached already, you could check this every time the app is started and would not need any buttons?

**Comment by gmh04** [comment]
related: https://github.com/edina/env-sys/issues/8

**Comment by gmh04** [comment]
Currently the number of zoom levels cached is the level at zoomToExtent + 3, see: https://github.com/edina/fieldtrip-offline-maps/blob/d2601a2ec10ccb2af8d2be4ee3f0c1456068d68d/src/www/js/offline-maps.js#L51

This can be tweaked once we get a feel for area size versus time it takes to download.
