### ISSUE TITLE
capture icon disappears when return to home page

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-cps#16]
On iOS the capture icon disappears when user returns to home page -  for example after viewing Map page or record list page. Not sure if this also happening on Android.

**Comment by gmh04** [comment]
make sure u using the latest, this was happening on android in an earlier version

**Comment by benismobile** [comment]
difficult issue to resolve. 
the section appears as expected in the DOM but is not being rendered by the WebView.
for the moment our work around is to remove the #home-page-capture div when user navigates away from the home page. (making sure this only happens for iOS).
