### ISSUE TITLE
style for textarea text is too light

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-cps#26]
text area text appears greyed out. should be normal black.

**Comment by benismobile** [comment]
the light text style probably makes sense for text area where text is default text in an editable text area. we probably want to apply this normal style if the textarea has been set to readOnly.

**Comment by gmh04** [comment]
related: https://github.com/edina/fieldtrip-cps/issues/17. This change needs to be deployed first.

**Comment by benismobile** [comment]
ok #17 is deployed now but I haven't added any class attributes. the text area field will have attribute "readOnly" or not at all, depending on editor property. Can you pick this up in css?

**Comment by gmh04** [comment]
yes you can, see commit
