### ISSUE TITLE
insert an image into form

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-cps#28]
client would like to be able to insert an image at the top of the form (after the introduction label) to make the experience of filling in form more visually appealing.

**Comment by benismobile** [comment]
this considered nice to have rather than essential

**Comment by benismobile** [comment]
known issues:
1. when image uploaded to text area in survey designer it does not show the image thumbnail
2. when survey is refreshed in browser or loaded from sid,the reference to the uploaded image is lost, if saved again the json will lose the reference to the img src.

**Comment by benismobile** [comment]
adding image to text area (description) widget is only a partial solution.
ideally we should have a new "static image" widget.

**Comment by gmh04** [comment]
This new type should be added to the documentation: https://github.com/edina/survey-designer/wiki/Specification
