### ISSUE TITLE
database backups

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-cps#31]
daily backups required, running back one month, backup taken every 4 hours.

**Comment by benismobile** [comment]
might be able to use AWS Glacier service for this?

**Comment by jollopre** [comment]
AWS Glacier seems a pretty flexible service to preserve unlimited number of archives and and amounts of data but I'm not sure if we can create backup plans or this is done automatically by the tool.

**Comment by benismobile** [comment]
think best way to find out is to try it (using the test server initially).
you'll probably need to get additional permission to use Glacier on Arcus Global  account.

**Comment by benismobile** [comment]
committed backup script into ansible
following issues remain:
1. need to rollover logs to prevent backup folder getting too large
2. need to create a script and cron on an EDINA server to scp the log files out of AWS domain.

**Comment by jollopre** [comment]
The rollover backups have been set up for 6 weeks duration (as per University policy).  The code that handles the backup sync to EDINA serve is committed at https://gitlab.edina.ac.uk/mobile/cat-census-infrastructure/commit/77eaf4640db4e2394ec061331ec9dca2b1db1d65
