### ISSUE TITLE
pc-api blocked in iOS 9

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-cps#37]
noticed that version 0.1.0 Bulwell Cat Watch does not render properly on iPad simulator in Xcode. debugging this seems to be an issue with iOS9 restrictions on connections not using TLS (https).

**Comment by benismobile** [comment]
workaround - add following access exception to plist in Xcode
<key>NSAppTransportSecurity</key>
   <dict>
     <key>NSAllowsArbitraryLoads</key>
     <true/>
     <key>NSExceptionDomains</key>
     <dict>
       <key>52.16.51.127</key>
       <dict>
         <key>NSExceptionAllowsInsecureHTTPLoads</key>
         <true/>
       </dict>
     </dict>
   </dict>

**Comment by gmh04** [comment]
@MapNavTom I suggest this is assigned to @jollopre.  I do not have IOS expertise or the time to do this.

**Comment by gmh04** [comment]
will be fixed by https://github.com/edina/fieldtrip-cps/issues/45
