### ISSUE TITLE
Add clearer upload buttons to the app

### ISSUE THREAD

**Issue by MapNavTom** [edina/fieldtrip-cps#44]
The iunterface need s to have clearer visual guidance to upload records collected.
1. Change the current upload button to say Upload
2. Exchange the hide /show records button with an Upload button
   3 Provide feedback on the process when a button is clicked on:

Uploading records
There are no records to upload

**Comment by jollopre** [comment]
This issue has involved the modification of different files. Below the commits performed:
- https://github.com/edina/fieldtrip-cps/commit/b5a1d293f5c032ae28aa48f4755f16b9afc87921
- https://github.com/edina/fieldtrip-cps/commit/630274e81cf50ec9cb605d4500458d0645da678e
- https://github.com/edina/fieldtrip-cps/commit/91c57c79d399364fb047c55916988e25be0a644d
- https://github.com/edina/fieldtrip-sync/commit/24ada84941ac99211fbeea44f9b25d8cdd588747
- https://github.com/edina/fieldtrip-open/commit/159c1235ed50002e947f66941598ac1b8963667c
