### ISSUE TITLE
HTTPS support for IOS app

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-cps#45]
Apple will no longer allow HTTP requests to be made from app after the end of October.  Therefore we need to:

1) put the pcapi behind HTTPS
2) update app to use new URL

Note: we need to create a Jisc Certificate Authority certificate: see https://www.ease.ed.ac.uk/admindocs/gencsr.html

**Comment by jollopre** [comment]
The certificate installation has been automatic through ansible. Specifically, the role apache from repository cat-census-infrastructure has been updated to include this requirement
