### ISSUE TITLE
Add ability to download surveys.

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-cps#8]
I'll initially add button to capture tab.  Survey will appear below.

**Comment by gmh04** [comment]
available in 0.0.2

**Comment by benismobile** [comment]
thanks working brilliantly

**Comment by benismobile** [comment]
Would be ideal if the form could be downloaded initially when user first opens app.
If this is possible change text for download survey button from "Download Survey: to "Update Survey"
